# Generated by Django 4.0.3 on 2022-03-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synergy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
